# _config.yml

# CS-499 ePortfolio

# Theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

# Title
title: Nicolas Valles - Computer Science Portfolio SNHU

# Description
description: Final Capstone Project and ePortfolio

exclude:
  - README.md
